[Feature] Add auto leave raid module
night/betterttv pull request #3394
Opened 2019-02-27 21:19 UTC by whitecrownclown

@night This PR should close #2936

2019-03-11 00:55 UTC, night commented on src/modules/auto_leave_raid/index.js
> +                        $(el).find('button').click();
probably should be more specific than clicking an arbitrary button, no?

2019-03-13 08:29 UTC, whitecrownclown commented
> is there a better way than mutation observer? can we instead catch this at a higher level inside of react (like we do for host mode)?

I think so, I'll have a look over it and update the PR.

2019-03-16 21:09 UTC, whitecrownclown commented
@night 	Couldn't do the same as `host mode` since the raid notifications are added from a WebSocket message (so the react context isn't available until the notification arrives). I've changed from "button click" (which wasn't reliable as it would also cancel the raid from the broadcaster) to calling `handleLeaveRaid` when the mutation triggers.

In the end, I couldn't really drop the mutation observer since I couldn't find any method to patch, as done in host mode.

2019-07-06 08:08 UTC, redwyre commented
Any update on this?

2019-11-07 14:56 UTC, whitecrownclown commented
@redwyre Waiting on a review atm

2020-08-30 22:04 UTC, night commented
@whitecrownclown similarly for this one.. this should be like 4 lines of observer code using the new system!

2020-08-30 22:05 UTC, night commented on src/modules/auto_leave_raid/index.js
> +            description: 'Automatically leaves raids'
nit: lets make this description be a little different than the name?

2020-08-30 22:05 UTC, night commented on src/modules/auto_leave_raid/index.js
> +            this.autoLeaveRaidObserver();
nit: we don't need `{}` on this

2020-08-30 22:05 UTC, night commented on src/modules/auto_leave_raid/index.js
> +            if (!settings.get('autoLeaveRaid')) {
nit: we don't need `{}` on this

2020-09-01 09:02 UTC, night commented
@whitecrownclown looks like this PR is in a bit of a mangled state.. you may need to merge master or rebase and exclude everything but your expected commits

2020-09-02 13:43 UTC, whitecrownclown commented
@night Yeah, I'm not sure what happened there, I did rebase, perhaps I messed it up somehow. I'll update the PR, there's still an issue I need to solve with the functionality.

2020-09-06 07:13 UTC, night commented
@whitecrownclown because safe emitter wraps the callback it is not possible for `off` to work in your code because the reference does not match. if you console log the output you will see the event handler does not get removed if you call off. the closure returned from `on` should work. if you can provide more information on the misbehavior you see i'm happy to take a look.

2020-09-06 07:28 UTC, night requested changes

2020-09-06 07:28 UTC, night commented on src/modules/auto_leave_raid/index.js
> +            name: 'Leave Raids Automatically',
this naming is inconsistent with the other automatic setting we're adding.. should this be `Auto-leave Raids`?

2020-09-06 07:28 UTC, night commented on src/modules/auto_leave_raid/index.js
> +            id: 'autoLeaveRaid',
`autoLeaveRaids`

2020-09-06 07:28 UTC, night commented on src/modules/auto_leave_raid/index.js
> +            description: 'Disable auto-joining a raid',
`Automatically removes you from future channel raids`

2020-09-06 07:28 UTC, night commented on src/modules/auto_leave_raid/index.js
> +        const raidContext = twitch.getChannelRaidContext(raidBanner.get(0));
do we actually need this raid context? can we detect this from the button state?

2020-09-06 07:28 UTC, night commented on src/utils/twitch.js
> +    getChannelHostingContext() {
rm

2020-09-06 07:28 UTC, night commented on src/modules/auto_leave_raid/index.js
> +            debug.log("Couldn't find raidContext - autoLeaveRaid module");
did you mean to leave this debug line in?

2021-04-24 03:52 UTC, ExploreTheFloor commented
What happened to this PR?

2021-08-28 19:07 UTC, night commented
closing due to inactivity, and superseded by #4683

2021-08-28 19:07 UTC, closed without merging