[Feature] Add automatic claim of bonus points
night/betterttv pull request #3642
Opened 2019-11-05 16:06 UTC by whitecrownclown

Closes #3616

@night Don't think this deserves a setting, what do you think?

Thanks!

2019-11-11 05:34 UTC, night commented
thanks for the PR. imo this definitely needs a setting, since it performs an action on behalf of the user

2019-11-11 10:42 UTC, whitecrownclown commented
I've added a setting for it.

2020-02-23 20:09 UTC, pmrt commented
Any news on this one @night? Looking forward to this feature!

2020-03-31 12:08 UTC, whitecrownclown commented
@night Hey, any updates on how we can get this merged? Thanks!

2020-08-31 06:58 UTC, night commented on src/modules/channel_points/index.js
> +            description: 'Automatically claim channel bonus points'
let's reword this to "Auto-claim Channel Points" and "Automatically claims bonus channel points"

2020-08-31 06:58 UTC, night commented on src/modules/channel_points/index.js
> +        const observe = (_watcher, element) => {
move this to the new dom observer

2020-09-04 09:54 UTC, whitecrownclown commented on src/modules/channel_points/index.js
> +        const observe = (_watcher, element) => {
done!

2020-09-06 07:20 UTC, night requested changes

2020-09-06 07:20 UTC, night commented on src/modules/channel_points/index.js
> +                { useParentNode: true }
im surprised the linter is not mad. can you remove these spaces

2020-09-06 07:20 UTC, night commented on src/modules/channel_points/index.js
> +    autoClaimBonusPoints() {
nit: `toggleAutoClaimBonusPoints`

2020-09-06 07:20 UTC, night commented on src/modules/channel_points/index.js
> +    hideChannelPoints() {
nit: `toggleHideChannelPoints`

2020-09-06 07:20 UTC, night commented on src/modules/channel_points/index.js
> +        watcher.on('load.channel', this.autoClaimBonusPoints);
we don't need to load this twice, as dom listeners persist

2020-09-06 07:20 UTC, night commented on src/modules/channel_points/index.js
> +            name: 'Auto-Claim Bonus Points',
`Auto-Claim Channel Points`

2020-09-06 07:20 UTC, night commented on src/modules/channel_points/index.js
> +            id: 'autoClaimBonusPoints',
`autoClaimBonusChannelPoints`

2020-09-06 07:20 UTC, night commented on src/modules/channel_points/index.js
> +        this.autoClaimBonusPoints();
we are never loading the `hideChannelPoints`

2020-10-05 06:32 UTC, merged