New option: Enable hypechat
night/betterttv pull request #6239
Opened 2023-06-26 21:47 UTC by DerValiser

Twitch released a new "feature" a few days ago: hypechat. These are chat messages pinned for money, just like Youtube Superchat. 

Besides the huge prices of up to 600 dollars, there is the problem that the streamer can NOT disable this feature. Currently, this is only for Twitch partners, but it will definitely be coming to all channels soon.

Following the existing code for bits, you can now also hide hypechat.

More information at: https://help.twitch.tv/s/article/hype-chat-by-twitch?language=en_US

2023-06-26 21:49 UTC, DerValiser commented
Hi BTTV Team,
this is my first pull request on Github. I hope I did everything right and did not violate any guidelines. Otherwise please let me know.

2023-06-27 10:39 UTC, dclstn requested changes

2023-06-27 10:39 UTC, dclstn commented on src/i18n/messages/de-DE.json
> +  "zgSj28": "Bewegt den Chat auf die linke Seite des Players.",
Undo any changes made to this file, this is handled via crowdin.

2023-06-27 10:39 UTC, dclstn commented on src/modules/hide_hypechat/style.css
> +      display: none !important;
What about hiding the actual hype chat messages?

2023-06-27 10:39 UTC, dclstn commented on src/modules/hide_hypechat/index.js
> +    this.load();
I would reverse this ordering, first load then attach the listener.

2023-06-27 10:39 UTC, dclstn commented on src/utils/legacy-settings.js
> +  HIDE_HYPECHAT: 'hideHypeChat',
Undo any changes made to this file, this is used to migrate the old settings into a dictionary.

2023-06-27 10:39 UTC, dclstn commented on src/modules/settings/components/settings/twitch/Chat.jsx
> +            <p className={styles.heading}>{formatMessage({defaultMessage: 'HypeChat'})}</p>
nit: `Hype Chat`

2023-06-27 10:39 UTC, dclstn commented on src/constants.js
> +  HYPECHAT: 1 << 7,
Change any references to `HYPE_CHAT` and `HIDE_HYPE_CHAT`

2023-06-27 10:39 UTC, dclstn commented on src/modules/hide_hypechat/index.js
> +    document.body.classList.toggle('bttv-hide-hypechat', !hasFlag(settings.get(SettingIds.CHAT), ChatFlags.HYPECHAT));
Some channels and pages don't have this button, I'd query for it and ensure it's there.

And then apply a style to the button, if it's set to be hidden.

2023-06-27 10:39 UTC, dclstn commented on src/modules/hide_hypechat/index.js
> +    this.load();
Could we listen for a mutation for this button? and then based on the result hide it.

2023-07-06 15:45 UTC, night commented
superceded by #6255 I think?

2023-07-06 15:45 UTC, closed without merging