[Fix] Replaced hardcoded 7tv cdn
night/betterttv pull request #6961
Opened 2024-07-23 21:47 UTC by FrantaBOT

Hello,
I've replaced the hardcoded 7TV emote url with the url from the api because it's going to cause problems in the future.

2024-07-28 19:23 UTC, night commented
appreciate the PR, but is there any link to a discussion or explanation of upstream changes?

2024-08-01 23:38 UTC, night requested changes

2024-08-01 23:38 UTC, night commented on src/modules/seventv/channel-emotes.js
> +          this.emotes.set(code, createEmote(id, code, url, animated, owner, category, isOverlay(flags)));
there are multiple places where `createEmote` is called that were missed

2024-08-01 23:38 UTC, night commented on src/modules/seventv/utils.js
> +export function createEmote(id, code, url, animated, owner, category, overlay) {
rather than adding an arg to the middle of the list, we prefer to add new args onto the end of the list

2024-08-01 23:38 UTC, night commented on src/modules/seventv/utils.js
> +  return `https:${url}/${version}${static_ ? '_static' : ''}.webp`;
is there any guarantee they won't add a scheme in front of the url? trailing slash?

2024-08-27 12:28 UTC, dclstn commented
Lgtm, just a few formatting issues and bug fix that are now fixed

2024-08-29 15:23 UTC, merged